### ISSUE TITLE
Recent issue with NodeJS reinstall

### ISSUE THREAD

**Issue by ghost** [dragonbanshee/node-steam-parentbot#28]
Uhm, I had to install NodeJS on a new server, but now when I run the bot(with the new ES6 update?) I get following error..

```
bots@box:~$ nodejs bots.js

/home/bots/bots.js:6
class ChildBot extends ParentBot {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

And this are my versions of Node & NPM

```
bots@box:~$ nodejs -v
v0.10.25
bots@box:~$ npm -v
1.3.10
```

I hope you really can help me here, since apt-get install node wont work. If required, I'm using Ubuntu 14.04.

**Comment by kjsmita6** [comment]
As the Readme says, you need to use at least node 4.0.0. 

Also since you use Ubuntu you can't use `apt-get install node` because node is something completely different. I would recommend using [nvm](https://github.com/creationix/nvm) to use node.

**Comment by mert574** [comment]
Please update your node version.

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by ghost** [comment]
Well I got it 'wokring' now thanks to infam0us, the problem is now, it asks me to check if I enabled a phone number on the account(Wich I took out recently, and switched back to E-Mail Guard Codes), the guard code itself gets sent fine to my E-Mail, but then this happens..

```
[Logged into steam stuff]

2016-05-13T01:15:35.063Z - info: [user] Logged into Steam web
2016-05-13T01:15:36.573Z - error: [user] Failed to enable two factor. Check if you have a phone number enabled for this account.
2016-05-13T01:15:36.577Z - error: [user] Error: Error 2
    at SteamCommunity.<anonymous> (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/components/twofactor.js:42:17)
    at Request._callback (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/components/http.js:62:14)
    at Request.self.callback (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/bots/node_modules/steam-parentbot/node_modules/steamcommunity/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
```

The funny thing is, the bot is online.

Also afterwards the bots wont do anything, no events will be called, and I cannot overwrite _onLogOnResponde. It simply is online, and thats it.

**Comment by kjsmita6** [comment]
You can ignore that error, because it is the same as the message above about no phone number (https://github.com/dragonbanshee/node-steam-parentbot/blob/master/parentbot.js#L177-178).

This method is called in _onLogOnResponse, so if you overwrite it in your code this error won't happen and the bot will not attempt to enable 2FA.

**Comment by ghost** [comment]
The thing is, I DID overwrite it, but the overwrite wont be accepted, nothing changes afterall, wont join groupchat nor send a message, only goes online.

```
class ChildBot extends ParentBot {
    _onLogOnResponde(response) {
        if (response.eresult === Steam.EResult.OK) {
            this.logger.info('Logged into Steam!');
            this.steamFriends.setPersonaState(Steam.EPersonaState = 1);
            this.steamFriends.joinChat('GroupID');
            this.steamFriends.sendMessage('SteamID', 'test');
        }
    }
}
```

**Comment by kjsmita6** [comment]
The ES6 one might not correctly overwrite stuff but i'm not sure. I'm pretty sure it does. Can you post your whole code?

**Comment by ghost** [comment]
```
'use strict' // must have 'use strict' at top


var ParentBot = require('steam-parentbot').ES6; // .ES6 for new version
var Steam = ParentBot.Steam; // Steam object


class ChildBot extends ParentBot {
    _onLogOnResponde(response) {
        if (response.eresult === Steam.EResult.OK) {
            this.logger.info('Logged into Steam!');
            this.steamFriends.setPersonaState(Steam.EPersonaState = 1);
            this.steamFriends.joinChat('');
            this.steamFriends.sendMessage('', 'test');
        }
    }
}

var Bot = new ChildBot('', '', {});


Bot.steamTrading.on('tradeProposed', function (tradeID, steamID) { //create your own listeners
    Bot.steamTrading.respondToTrade(tradeID, false);
    Bot.logger.verbose('Trade request from ' + steamID);
});


Bot.connect(); //connect to Steam

Bot.steamFriends.on('chatEnter', function(id, response) {
    console.log(response);
})
```

The thing is, the example says const, but the front page says var? Does it matter much wich to use?

**Comment by originalwhitestar** [comment]
*bump* Since I really need to get the bot working, sorry.

**Comment by kjsmita6** [comment]
I don't know what ybe problem is and I don't have time to fix it right now. Your ever bet would be to use the older version of parentbot.

**Comment by originalwhitestar** [comment]
Well I switched, now I get this error --

```
util.js:839
    throw new TypeError('The super constructor to "inherits" must ' +
    ^

TypeError: The super constructor to "inherits" must have a prototype
    at Object.exports.inherits (util.js:839:11)
    at Object.<anonymous> (/home/bots/bots.js:9:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

Code:

```
var util = require('util');
var ParentBot = require('steam-parentbot'); //change to 'steam-parentbot' if not running from examples directory
var Steam = ParentBot.Steam; // Steam object

var ChildBot = function () {
    ChildBot.super_.apply(this, arguments);
}

util.inherits(ChildBot, ParentBot);
[...]
```

**Comment by ghost** [comment]
Same error there with 2FA, bot only comes online and then nothing works from the code.

```
var util = require('util');
var ParentBot = require('steam-parentbot').ParentBot; //change to 'steam-parentbot' if not running from examples directory
var Steam = ParentBot.Steam; // Steam object

var ChildBot = function () {
    ChildBot.super_.apply(this, arguments);
}

util.inherits(ChildBot, ParentBot);

var Bot = new ChildBot('', '', {});

ChildBot.prototype._onLogOnResponde = function (response) {
    if (response.eresult === Steam.EResult.OK) {
        this.logger.info('Logged into Steam!');
        this.steamFriends.setPersonaState(Steam.EPersonaState = 1);
        this.steamFriends.joinChat('');
        this.steamFriends.sendMessage('', 'test');
    }
}


Bot.steamTrading.on('tradeProposed', function (tradeID, steamID) { //create your own listeners
    Bot.steamTrading.respondToTrade(tradeID, false);
    Bot.logger.verbose('Trade request from ' + steamID);
});


Bot.connect(); //connect to Steam

Bot.steamFriends.on('chatEnter', function(id, response) {
    console.log(response);
});
```

**Comment by ghost** [comment]
EDIT: Fuck my life, I miswrote response. FIXED.
