### ISSUE TITLE
Array of bots and handlers

### ISSUE THREAD

**Issue by vanakulka** [dragonbanshee/node-steam-parentbot#33]
Hello, I created array of bots.
I setup handlers like in example, so basically ChildBot.prototype.... But how can I know on which bot happened that action.
So if someone write to chat to one of my bots, I want only from that one bot to respond.
Is that possible?

**Comment by kjsmita6** [comment]
Each bot has its own set of listeners and handlers so the not with a certain handler will be the only one to respond. 

Each one also has the username in the logger so you will know which bot is logging what.

**Comment by vanakulka** [comment]
So if I go something like -- Bot[1].prototype._onFriend = function(steamID, relationship) {
    }
It will create handler for specific bot?

**Comment by kjsmita6** [comment]
If `Bot` is your array of bots yeah it should. 

I've never used multiple bots like this so this is all untested but I think it should work.

**Comment by vanakulka** [comment]
Tried this -- Not an array, only bot object.
`bot.prototype._onFriendMsg = function (steamID, message, type) { 
    if (type === Steam.EChatEntryType.ChatMsg) {
        if (message != '!prices') {
            this.logger.info(steamID + ' sent: ' + message);
            Bot.steamFriends.sendMessage(steamID, "FUCK YOU"); 
        }
    }
    else {
        console.log(type);
    }
}`
Bot is created like this --
`var bot = new ChildBot("thevanak", "06081998Petr", {
    apikey: "993EA54B3BDD7F418C6F8EC610391FD9", 
    sharedSecret: "uARU7nGY4Rgax1MhhWNwK2W5kic=",
    identitySecret: "5WKMqFgdELFaTRhhOoqwKvbWfnE=",
    confirmationInterval: 10000, 
    richPresenceID: 730
});
bot.connect();`

Of course that I created and connected bot first and after that in code I created handler.

Gives me this error --
`C:\Users\vanak\Node.js\steam_bot\bot.js:67
bot.prototype._onFriendMsg = function (steamID, message, type) { //overwrite default event handlers
                           ^

TypeError: Cannot set property '_onFriendMsg' of undefined
    at Object.<anonymous> (C:\Users\vanak\Node.js\steam_bot\bot.js:67:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

**Comment by kjsmita6** [comment]
You cannot call bot.prototype, if you want to create a listener for that
you need to do `Bot.steamFriends.on('friendMsg', ...`

**Comment by vanakulka** [comment]
You should have there donate button, because you answer in minutes and you really want to help^^.
Why the hell bot sends my message and this message - " Hi, thanks for messaging me! If you are getting this message, it means that my owner hasn't configured me properly. Annoy them with messages until they do!" 
But really, make a donation button for you! :D

**Comment by dragonbanshee** [comment]
I don't help for donations, I help because I want to help :).

It sends the message because Childbot.prototype._onFriendMsg isn't being
overridden. If you want to make it not send that and have each bot send its
own message you could do something like this:

```javascript
Childbot.prototype._onFriendMsg = function(steamID, message, type) { });
```

And just keep it blank. Like I said I've never done this before but I feel
like it should work.

**Comment by kjsmita6** [comment]
I don't help for donations, I help because I want to help :).

It sends the message because Childbot.prototype._onFriendMsg isn't being
overridden. If you want to make it not send that and have each bot send its
own message you could do something like this:

```javascript
Childbot.prototype._onFriendMsg = function(steamID, message, type) { });
```

And just keep it blank. Like I said I've never done this before but I feel
like it should work.

**Comment by vanakulka** [comment]
Thank you so much. And last one thing. How can I get cookies and sessionID from login?

**Comment by kjsmita6** [comment]
Cookies are stored in their respective modules. Session ID is Bot.steamClient.sessionID.

**Comment by kjsmita6** [comment]
Closing due to inactivity.
