### ISSUE TITLE
Error: This account is not authorized to use this feature.

### ISSUE THREAD

**Issue by mert574** [dragonbanshee/node-steam-parentbot#8]
Hello.
When I try to use your example code, I'm getting this output:

```
2016-01-31T14:09:24.725Z - info: [**] Using sentry file **.sentry
2016-01-31T14:09:24.733Z - silly: [**] connecting to 72.165.61.174:27017
2016-01-31T14:09:24.738Z - debug: [**] Connecting to Steam...
2016-01-31T14:09:24.899Z - silly: [**] connected
2016-01-31T14:09:25.065Z - silly: [**] encrypt request
2016-01-31T14:09:25.256Z - verbose: [**] Connected to Steam, logging in...
2016-01-31T14:09:25.257Z - debug: [**] Logging in...
2016-01-31T14:09:25.643Z - info: [**] Logged into Steam!
2016-01-31T14:09:25.970Z - info: [**] Logged into Steam web
2016-01-31T14:09:26.802Z - error: [**] Error: This account is not authorized to use this feature.
    at SteamCommunity._checkCommunityError (/root/down/**/node_modules/steamcommunity/index.js:344:12)
    at Request._callback (/root/down/**/node_modules/steamcommunity/components/webapi.js:54:11)
    at Request.self.callback (/root/down/**/node_modules/steamcommunity/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/root/down/**/node_modules/steamcommunity/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Gunzip.<anonymous> (/root/down/**/node_modules/steamcommunity/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)


```

To be more clear, this is the code that I'm using to test/recreate

```
var ChildBot = function () { ChildBot.super_.apply(this, arguments); }
require('util').inherits(ChildBot, require('steam-parentbot'));

var Bot1 = new ChildBot('**', 'p@$$wd!', {
  sharedSecret: 's€cR3T/sT34m'
}).connect();
```

**Notes**
- I've more than 5 usd in my steam wallet
- I have a game
- Account level is 1 ( acc link: http://steamcommunity.com/id/**/ )
- I have access to Steam Web API key (from here: https://steamcommunity.com/dev/apikey )
- I can send friend invites and I added some friends
- Community Market is not avaliable yet (because I've newly activated the mobile auth (maybe. not sure) )
- I'm also getting the same error on this page : https://steamcommunity.com/chat/ {

> Sorry!
> An error was encountered while processing your request:
> 
> This account is not authorized to use this feature.

}
- Nothing changes when I try to pass apikey and/or twoFactorCode manually
- Node version: v4.1.1

Why I'm getting this error? I'm just trying to connect to my account. Nothing else. I'm not trying to buy/trade items, stay online on chat etc..

**UPDATE**
I'm also having another error when I pass richPresenceID.I think both errors are related

```
/path/**/node_modules/steam-parentbot/parentbot.js:37
    this.steamRichPresence = (this.options.richPresenceID ? new Steam.steamRichPresence(this.steamClient, parseInt(this.options.richPresenceID)) : undefined);
                                                            ^

TypeError: Steam.steamRichPresence is not a function
    at options.steamClient.on.steamClient.on.steamUser.on.steamFriends.on (/path/**/node_modules/steam-parentbot/parentbot.js:37:61)
    at new ChildBot (/path/**/bot.js:1:108)
    at Object.<anonymous> (/path/**/bot.js:4:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by kjsmita6** [comment]
The fact that you can't see chat show's that your account is limited, but you said you have more that 5 dollars. Maybe try buying a game and see if that fixes it.

**Comment by mert574** [comment]
Bought a game, now account is level 1. Everything else is same.
Edit:
After getting the error, bot is not stopping/closing. When I pass gamePlayed: '49520', my account is being in-game until I ctrl+c it twice. Idk why I need to do it twice

**Comment by kjsmita6** [comment]
Having to control-c twice is standard for closing things usually. I just saw your edit and it was a typo on my part and it's fixed, but I don't think the problem is related.

If you can't see the chat window in the browser, but can access the steam api and have bought a game and spent $5 I think there's nothing I can do, since it seems like a problem with steam at this point.

**Comment by mert574** [comment]
You are right @dragonbanshee ! It was a steam related problem. I've done nothing but sending a ticket to them and problem is solved now. Thanks!

Edit: but the oher problem about "richPresenceID" still exists. I don't even know what that is so I'm not opening a new issue about it.
