### ISSUE TITLE
Error after Logged into Steam web

### ISSUE THREAD

**Issue by eXoCoding** [dragonbanshee/node-steam-parentbot#9]
Hey, can someone tell me how i can fix this error. Thanks for incomming help.

`
2016-02-01T23:11:52.019Z - error: [BOTNAME] Error: This account is not authorized to use this feature.
    at SteamCommunity._checkCommunityError (/root/bots/node_modules/steamcommunity/index.js:344:12)
    at Request._callback (/root/bots/node_modules/steamcommunity/components/webapi.js:54:11)
    at Request.self.callback (/root/bots/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/root/bots/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at Gunzip.<anonymous> (/root/bots/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
`

**Comment by kjsmita6** [comment]
Someone recently had this error in #8, make sure your account meets the requirements for a non-limited user (must spend > $5 on steam).

**Comment by eXoCoding** [comment]
well i allready did thats the problem

**Comment by eXoCoding** [comment]
i used this account already as trade bot but only with e-mail validation on trades. i want it now on f2a.

**Comment by mert574** [comment]
After activating/reactivating the 2fa, you will be limited for 2 weeks. You cannot trade in that time. I think that's why you are limited.
To see more detailed info about your limit, you can look into this page: http://steamcommunity.com/market/

**Comment by eXoCoding** [comment]
is there really a connection between market (ban in market is logic) and chat?. The point is i cant really log in (using parentbot) and that is strange. i mean i have access to api key and i can send chat messages and so on. I wrote also to steam support like in #8.

**Comment by eXoCoding** [comment]
not correctly working until now. steam support fails as well. i will ignore that message and close this issue.
